authForumDB: &authForumDB
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tmello
  password:
  host: localhost

development:
  <<: *authForumDB
  database: authForum_development

test:
  <<: *authForumDB
  database: authForum_test

production:
  <<: *authForumDB
  database: authForum_production
